pipeline {
    agent any 
    
    tools{
        jdk 'java'
        maven 'maven'
    }
    environment {
        SCANNER_HOME=tool 'sonar-scanner'
    }
    stages{
        stage("Git Checkout"){
            steps{
                git branch: 'main', changelog: false, poll: false, url: 'https://github.com/jaiswaladi246/Petclinic.git'
            }
        }
        stage("Compile"){
            steps{
                sh "mvn clean compile"
            }
        }	
        stage("Sonarqube Analysis "){
            steps{
                withSonarQubeEnv('sonar-server') {
                    sh ''' $SCANNER_HOME/bin/sonar-scanner -       Dsonar.projectName=simplejavaproject \
                    -Dsonar.java.binaries=. \
                    -Dsonar.projectKey=simplejavaproject '''
    
                }
            }
        }
    }
}
