apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  name: gp2-encrypted
parameters:
  fsType: ext4
  type: gp2
  encrypted: "true"
provisioner: kubernetes.io/aws-ebs
reclaimPolicy: Delete
volumeBindingMode: Immediate

https://jfrog.com/help/r/jfrog-installation-setup-documentation/install-artifactory-single-node-with-helm-charts

psql -h <endpoint> -p 5432 -U <username> -d <dbname>

ALTER DATABASE jfrogdb OWNER TO postgres ;
GRANT ALL PRIVILEGES ON DATABASE jfrogdb TO postgres;

